version: "3.9"
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      STREAMLIT_SERVER_PORT: 8514
      AIRTABLE_API_KEY:
      DB_DSN:
    ports:
      - 127.0.0.1:8514:8514
